local map = function(Mode, Key, Cmd, Desc)
	vim.keymap.set(Mode, Key, Cmd, Desc)
end
----------------------------------------Split config----------------------------------------
map("n", "<leader>ow", "<cmd>vsplit<cr>", { desc = " Vsplit" }) -- vsplit
map("n", "<leader>os", "<cmd>split<cr>", { desc = " Split" }) -- split
----------------------------------------Buffer----------------------------------------
map("n", "<leader>obd", "<cmd>BufferDelete<cr>", { desc = "Buffer Delete" })
map("n", "<leader>obl", "<cmd>BufferPickDelete<cr>", { desc = "Buffer Pick Delete" })
map("n", "<leader>obp", "<cmd>BufferPick<cr>", { desc = "Buffer Pick" })
map("n", "<leader>obn", "<cmd>BufferNext<cr>", { desc = "Buffer Next" })
----------------------------------------Line Move----------------------------------------
map({ "n" }, "<A-k>", "<cmd>m .-2<cr>==", { silent = true, desc = "Move line up" }) -- Move line up
map({ "n" }, "<A-j>", "<cmd>m .+1<cr>==", { silent = true, desc = "Move line down" }) -- Move line down
map({ "v" }, "<A-k>", "<cmd>m '<-2<cr>gv=gv", { silent = true, desc = "Move line up" }) -- Move line up
map({ "v" }, "<A-j>", "<cmd>m '>+1<cr>gv=gv", { silent = true, desc = "Move line up" }) -- Move line up
----------------------------------------Use hjkl Move----------------------------------------
map("i", "jk", "<Esc>")
map("i", "kj", "<Esc>")
map({ "n", "i", "v" }, "<Left>", "<Nop>")
map({ "n", "i", "v" }, "<Right>", "<Nop>")
map({ "n", "i", "v" }, "<Up>", "<Nop>")
map({ "n", "i", "v" }, "<Down>", "<Nop>")
----------------------------------------Window Move----------------------------------------
map({ "n", "i", "v" }, "<C-k>", "<C-w>k")
map({ "n", "i", "v" }, "<C-j>", "<C-w>j")
map({ "n", "i", "v" }, "<C-l>", "<C-w>l")
map({ "n", "i", "v" }, "<C-h>", "<C-w>h")
----------------------------------------Outline----------------------------------------
map("n", "<leader>oa", "<cmd>AerialToggle!<CR>", { desc = "Outline" })
----------------------------------------Flash----------------------------------------
map({ "n", "x", "o" }, "s", function()
	require("flash").jump()
end, { desc = "Flash" })
map({ "n", "x", "o" }, "S", function()
	require("flash").treesitter()
end, { desc = "Flash Treesitter" })
map("o", "r", function()
	require("flash").remote()
end, { desc = "Remote Flash" })
map({ "o", "x" }, "R", function()
	require("flash").treesitter_search()
end, { desc = "Treesitter Search" })
map({ "o", "x" }, "<c-s>", function()
	require("flash").treesitter_search()
end, { desc = "Treesitter Search" })
----------------------------------------Scissors----------------------------------------
map("n", "<leader>se", function()
	require("scissors").editSnippet()
end, { desc = "Snippet: Edit" })

-- when used in visual mode, prefills the selection as snippet body
map({ "n", "x" }, "<leader>sa", function()
	require("scissors").addNewSnippet()
end, { desc = "Snippet: Add" })
------------------------------------------Explorer----------------------------------------
map("n", "<leader>e", "<cmd>Neotree<cr>", { desc = "Neo-tree" })
map("n", "<leader>-", "<CMD>Oil<CR>", { desc = "Open parent directory" })
----------------------------------------lsp----------------------------------------
map("n", "gD", "<CMD>FzfLua lsp_declarations<CR>", { desc = "[G]oto [D]eclaration" })
map("n", "gd", "<CMD>FzfLua lsp_definitions<CR>", { desc = "[G]oto [D]efinition" })
map("n", "K", vim.lsp.buf.hover, { desc = "Hover Documentation" })
map("n", "gi", "<cmd>FzfLua lsp_implementations<CR>", { desc = "[G]oto [I]mplementation" })
map("n", "<C-k>", vim.lsp.buf.signature_help, { desc = "Signature Documentation" })
map("n", "grn", vim.lsp.buf.rename, { desc = "[R]e[n]ame" })
map("n", "gca", "<cmd>FzfLua lsp_code_actions<cr>", { desc = "[C]ode [A]ction" })
map("n", "grr", "<cmd>FzfLua lsp_references<cr>", { desc = "[G]oto [R]eferences" })
----------------------------------------FzfLua----------------------------------------
map("n", "<leader>fll", "<CMD>FzfLua<CR>", { desc = "FzfLua Modle Chose" })
map("n", "<leader>fm", "<CMD>FzfLua manpages<CR>", { desc = "FzfLua manpages" })
map("n", "<leader>fp", "<CMD>FzfLua packadd<CR>", { desc = "FzfLua Install PACK List" })
map("n", "<leader>ff", "<CMD>FzfLua files<CR>", { desc = "FzfLua Files" })
map("n", "<leader>fb", "<CMD>FzfLua buffers<CR>", { desc = "FzfLua Buffers" })
map("n", "<leader>f?", "<CMD>FzfLua helptags<CR>", { desc = "FzfLua Helptags" })
map("n", "<leader><leader>", "<CMD>FzfLua buffers<CR>", { desc = "FzfLua Buffers" })
map("n", "<leader>fw", "<CMD>FzfLua live_grep<CR>", { desc = "FzfLua Live_grep" })
map("n", "<leader>fu", "<CMD>FzfLua undotree<CR>", { desc = "FzfLua Undotree" })
map("n", "<leader>fld", "<CMD>FzfLua lsp_definitions<CR>", { desc = "FzfLua Lsp Definitions" })
map("n", "<leader>flr", "<CMD>FzfLua lsp_references<CR>", { desc = "FzfLua Lsp References" })
map("n", "<leader>fls", "<CMD>FzfLua diagnostics_workspace<CR>", { desc = "FzfLua Diagnostics Workspace" })
map("n", "<leader>fcc", "<CMD>FzfLua commands<CR>", { desc = "FzfLua Commands" })
map("n", "<leader>fcf", "<CMD>FzfLua complete_file<CR>", { desc = "FzfLua Complete File" })
map("n", "<leader>fcp", "<CMD>FzfLua complete_path<CR>", { desc = "FzfLua Complete Path" })
----------------------------------------Dap----------------------------------------
map("n", "<F5>", function()
	require("dap").continue()
end)
map("n", "<F10>", function()
	require("dap").step_over()
end)
map("n", "<F11>", function()
	require("dap").step_into()
end)
map("n", "<F12>", function()
	require("dap").step_out()
end)
map("n", "<Leader>db", function()
	require("dap").toggle_breakpoint()
end, { desc = "[DAP] Dap Toggle Breakpoint" })
map("n", "<Leader>dB", function()
	require("dap").set_breakpoint()
end, { desc = "[DAP] Dap Set Breakpoint" })
map("n", "<Leader>dp", function()
	require("dap").set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
end, { desc = "[DAP] Breakpoint Log" })
map("n", "<Leader>dr", function()
	require("dap").repl.open()
end, { desc = "[DAP] Repl Open" })
map("n", "<Leader>dl", function()
	require("dap").run_last()
end, { desc = "[DAP] Run Last" })
map({ "n", "v" }, "<Leader>dh", function()
	require("dap.ui.widgets").hover()
end, { desc = "[DAP] Dap Hover" })
map({ "n", "v" }, "<Leader>dp", function()
	require("dap.ui.widgets").preview()
end, { desc = "[DAP] Dap Preview" })
map("n", "<Leader>df", function()
	local widgets = require("dap.ui.widgets")
	widgets.centered_float(widgets.frames)
end)
map("n", "<Leader>ds", function()
	local widgets = require("dap.ui.widgets")
	widgets.centered_float(widgets.scopes)
end)
----------------------------------------ToggleTerm----------------------------------------
map("n", "<leader>tt", "<cmd>ToggleTerm<cr>", { desc = "ToggleTerm Term" })
map("n", "<leader>tf", "<cmd>ToggleTerm direction=float<cr>", { desc = "ToggleTerm Float" })
----------------------------------------Ai----------------------------------------
map({ "n", "x" }, "<leader>ca", function()
	require("opencode").ask("@this: ", { submit = true })
end, { desc = "Ask opencode…" })
map({ "n", "x" }, "<leader>cx", function()
	require("opencode").select()
end, { desc = "Execute opencode action…" })
map({ "n", "t" }, "<leader>c.", function()
	require("opencode").toggle()
end, { desc = "Toggle opencode" })

map({ "n", "x" }, "<leader>cgo", function()
	return require("opencode").operator("@this ")
end, { desc = "Add range to opencode", expr = true })
map("n", "<leader>cgoo", function()
	return require("opencode").operator("@this ") .. "_"
end, { desc = "Add line to opencode", expr = true })

map("n", "<leader>csu", function()
	require("opencode").command("session.half.page.up")
end, { desc = "Scroll opencode up" })
map("n", "<leader>csd", function()
	require("opencode").command("session.half.page.down")
end, { desc = "Scroll opencode down" })

-- You may want these if you use the opinionated `<C-a>` and `<C-x>` keymaps above — otherwise consider `<leader>o…` (and remove terminal mode from the `toggle` keymap)
map("n", "+", "<leader>ca", { desc = "Increment under cursor", noremap = true })
map("n", "-", "<leader>ca", { desc = "Decrement under cursor", noremap = true })
----------------------------------------Overseer----------------------------------------
map("n", "<F4>", "<cmd>OverseerRun<cr>", { desc = "List overseer templates" })
map("n", "<leader>rr", "<cmd>OverseerRun<cr>", { desc = "List overseer templates" })
map("n", "<leader>rt", "<cmd>OverseerToggle<cr>", { desc = "Toggle overseer tasks list" })
map("n", "<leader>ra", "<cmd>OverseerTaskAction<cr>", { desc = "Toggle overseer tasks action" })
