vim.pack.add({ "https://github.com/ibhagwan/fzf-lua", "https://github.com/nvim-tree/nvim-web-devicons" })
require("fzf-lua").setup()
local map = function(Mode, Key, Cmd, Desc)
	vim.keymap.set(Mode, Key, Cmd, Desc)
end
map("n", "<leader>fll", "<CMD>FzfLua<CR>", { desc = "FzfLua Modle Chose" })
map("n", "<leader>fm", "<CMD>FzfLua manpages<CR>", { desc = "FzfLua manpages" })
map("n", "<leader>fp", "<CMD>FzfLua packadd<CR>", { desc = "FzfLua Install PACK List" })
map("n", "<leader>ff", "<CMD>FzfLua files<CR>", { desc = "FzfLua Files" })
map("n", "<leader>fb", "<CMD>FzfLua buffers<CR>", { desc = "FzfLua Buffers" })
map("n", "<leader>f?", "<CMD>FzfLua helptags<CR>", { desc = "FzfLua Helptags" })
map("n", "<leader><leader>", "<CMD>FzfLua buffers<CR>", { desc = "FzfLua Buffers" })
map("n", "<leader>fw", "<CMD>FzfLua live_grep<CR>", { desc = "FzfLua Live_grep" })
map("n", "<leader>fu", "<CMD>FzfLua undotree<CR>", { desc = "FzfLua Undotree" })
map("n", "<leader>fld", "<CMD>FzfLua lsp_definitions<CR>", { desc = "FzfLua Lsp Definitions" })
map("n", "<leader>flr", "<CMD>FzfLua lsp_references<CR>", { desc = "FzfLua Lsp References" })
map("n", "<leader>fls", "<CMD>FzfLua diagnostics_workspace<CR>", { desc = "FzfLua Diagnostics Workspace" })
map("n", "<leader>fcc", "<CMD>FzfLua commands<CR>", { desc = "FzfLua Commands" })
map("n", "<leader>fcf", "<CMD>FzfLua complete_file<CR>", { desc = "FzfLua Complete File" })
map("n", "<leader>fcp", "<CMD>FzfLua complete_path<CR>", { desc = "FzfLua Complete Path" })
